blog/urls.py
from django.urls import path

from .views import ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleUpdateView, ArticleListView,ContactUsView

app_name = 'blog'

urlpatterns = [

    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article_details'),
    path('articles/update/<int:pk>/', ArticleUpdateView.as_view(), name='article_update'),
    path('articles/delete/<int:pk>/', ArticleDeleteView.as_view(), name='article_delete'),
    path('contacts/', ContactUsView.as_view(), name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='photos/', verbose_name='Изображение')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='Опубликован')
    number_of_views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title} {self.description} {self.is_published}'


    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ['title']

blog/views.py
from .models import Blogpost
from django.db.models import F
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class ArticleListView(ListView):
    model = Blogpost
    template_name = 'blog/articles.html'
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = super().get_queryset()
        return Blogpost.objects.filter(is_published=True)


class ArticleCreateView(CreateView):
    model = Blogpost
    fields = ['title', 'description']
    template_name = 'blog/article_form.html'
    success_url = reverse_lazy('blog:articles')


class ArticleDetailView(DetailView):
    model = Blogpost
    template_name = 'blog/article_details.html'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        # Retrieve the object using the parent's get_object method
        obj = super().get_object(queryset)

        # Safely increment the view count using an F() expression
        obj.views_count = F('number_of_views') + 1
        obj.save(update_fields=['number_of_views'])

        # Reload the object from the database to get the new view count
        obj.refresh_from_db()
        return obj

    # def get(self, request, *args, **kwargs):
    #     # Perform the increment before rendering the view
    #     art = self.get_object()
    #     Blogpost.objects.filter(pk=art.pk).update(number_of_views= art.number_of_views + 1)
    #     return super().get(request, *args, **kwargs)


class ArticleUpdateView(UpdateView):
    model = Blogpost
    fields = ['title', 'description']
    template_name = 'blog/article_form.html'

    def get_success_url(self):
        return reverse_lazy('blog:article_details', kwargs={'pk': self.object.pk})


class ArticleDeleteView(DeleteView):
    model = Blogpost
    template_name = 'blog/article_confirm_delete.html'
    success_url = reverse_lazy('blog:articles')


class ContactUsView(TemplateView):
    fields = ['name', 'email', 'message']
    template_name = 'blog/contacts.html'
    success_url = reverse_lazy('catalog:contacts')

blog/templates/blog/article_confirm_delete.html
<!-- blog/article_confirm_delete.html -->
{% extends 'blog/base.html' %}

{% block title %}Удаление статьи{% endblock %}

{% block content %}
{% include 'blog/header.html' %}

<h2>Удаление статьи</h2>
<p>Вы действительно хотите удалить "{{ blogpost.title }}"?</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Подтвердить</button>
    <a href="{% url 'blog:articles' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock %}

blog/templates/blog/article_details.html
<!-- blog/article_details.html -->
{% extends 'blog/base.html' %}

{% block title %}Статья{% endblock %}

{% block content %}
{% include 'blog/header.html' %}
<p>Изображение: <img src="{{ blog.photos.url }}" alt="{{ article.title }}"></p>
<h2>{{ article.title }}</h2>
<p>{{ article.description }}</p>
<p>Просмотров: {{ article.number_of_views }}</p>


<a href="{% url 'blog:article_update' article.pk %}" class="btn btn-secondary">Редактировать</a>
<a href="{% url 'blog:article_delete' article.pk %}" class="btn btn-danger">Удалить</a>
<a href="{% url 'blog:articles' %}" class="btn btn-primary">Вернуться к списку</a>

{% endblock %}

blog/templates/blog/article_form.html
<!-- blog/article_form.html -->
{% extends 'blog/base.html' %}

{% block title %}Новая статья{% endblock %}

{% block content %}
{% include 'blog/header.html' %}
<h2>Новая статья</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'blog:articles' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock %}

blog/templates/blog/articles.html
<!-- blog/articles.html -->

{% extends 'blog/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
{% include 'blog/header.html' %}
<div class="row text-center">
    {% for article in articles %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>
                        {{article.description|truncatechars:100}}
                    </li>
                    <li>Просмотров: {{ article.number_of_views }}</li>
                </ul>
                <div class="btn-group">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_details' article.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/base.html
<!-- blog/base.html -->

<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%}Blog: Home{% endblock %}</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Blog</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:articles' %}">Все статьи</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:contacts' %}">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:article_create' %}">Добавить статью</a>
        </nav>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        Blog
                        <small class="d-block mb-3 text-muted">&copy; 2025</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Разделы</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Автомобили</a></li>
                            <li><a class="text-muted" href="#">Самолеты</a></li>
                            <li><a class="text-muted" href="#">Поезда</a></li>
                            <li><a class="text-muted" href="#">Технологии</a></li>
                            <li><a class="text-muted" href="#">Другое</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Дополнительно</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="/blog/contacts/">Мы пишем</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>О нас</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="/blog/contacts/">Контакты</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
    </div>
    <!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/contacts.html
<!-- blog/contacts.html -->

{% extends 'blog/base.html' %}

{% block title %}Контакты{% endblock %}

{%block content%}
{% include 'blog/header.html' %}

<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/header.html
<!-- blog/header.html -->
<header>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Blog</h1>
        <p class="lead">Blog - это отличный партнер для познания мира техники</p>
    </div>
</header>